### ISSUE TITLE
Container: FootContainer

### ISSUE THREAD

**Issue by TadaTeruki** [p2hacks2023/pre-06#13]
下側のUIを格納

# 依存

なし

# 被依存

#16 

# パラメータ

children

# プレビュー

![A6C21AC5-1592-4D96-9AC0-B29F0FA7EF1E](https://github.com/p2hacks2023/pre-06/assets/69315285/031c2f90-2087-4bf6-a1f6-355a999afd47)
![E417E174-105A-4E63-9BC4-27C5C87E9A1F](https://github.com/p2hacks2023/pre-06/assets/69315285/cb440433-6dc2-40ac-a31f-2aa726c632a5)

**Comment by jugesuke** [comment]
Reactをやめたことに不要になった
https://github.com/p2hacks2023/pre-06/discussions/31
