### ISSUE TITLE
Container: HeadContainer

### ISSUE THREAD

**Issue by TadaTeruki** [p2hacks2023/pre-06#14]
上側のUIを挿入

# 依存

なし

# 被依存

#16 

# パラメータ

children

# プレビュー
![1B6BD9CF-A580-4C8C-A1F0-F2F5658DF1F6](https://github.com/p2hacks2023/pre-06/assets/69315285/b0cb27cc-ea69-41c8-ab49-b55fa0bf8ef5)
![C1285B58-AEA8-4375-980E-F6B59404E79D](https://github.com/p2hacks2023/pre-06/assets/69315285/d24b669f-b996-4c2b-be65-497d6b9a68d8)

**Comment by jugesuke** [comment]
Reactをやめたことに不要になった
https://github.com/p2hacks2023/pre-06/discussions/31
