### ISSUE TITLE
チュートリアルに載せる内容

### ISSUE THREAD

**Issue by TadaTeruki** [p2hacks2023/pre-06#18]
なにか欲しい
とりあえずテキストのみで十分

#17

**Comment by Yourein** [comment]
後で書きます

**Comment by Yourein** [comment]
> 後で書きます

これ明日(2023/12/12)の夜までにはどっかに上げます

**Comment by Yourein** [comment]
とりあえず暫定版
あんまり文章詰め詰めにしても見づらいだけだから、文章量は少なめにしてる

https://scrapbox.io/fung/%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB%E3%81%AB%E8%BC%89%E3%81%9B%E3%82%8B%E5%86%85%E5%AE%B9
