### ISSUE TITLE
React + Vite は厳しいかもしれない

### ISSUE THREAD

**Issue by jugesuke** [p2hacks2023/pre-06#21]
## Why 
React + Canvas がかなりやりづらいところがある
そのため、この問題を解決できるように設計を変える必要がある

## What
具体的には、React側の画面更新とCanvas側の変更を、うまく同期しないと壊れる
このプロダクトは Web APP っぽくなくて、どちらかというと html5 game っぽいため、Reactのエコシステムと合わない部分が大きい

**Comment by jugesuke** [comment]
Webアプリとしてなんとかするなら、解決策として考えられるのは以下

- Vanilla js で頑張る
- なんらか2dゲーム用のframeworkを使う
- gameが動くsciene だけvanilla で書いて切り替える

## Vanilla js

### いいとこ
- 実装やったことがある
- Canvas が使える

### きびしいところ
- 共同開発にあったecosystemかが微妙
- react等のframeworkの恩恵を受けられない
- 自前実装が増える

## 2dゲーム用のframework

### いいところ
- Game用であるから、欲しい機能は多分ある

### きびしいところ
- 使ったことなさすぎ、死

## gameが動くsciene だけvanilla で書いて切り替える

### いいところ
- Reactが使える？

### きびしいところ
- inter-pageのデータ共有が無理
- この方法だとReactのうまみが正直ない

**Comment by Yourein** [comment]
この回答がどれくらい的を射ているかわからないんだけど、p5js埋め込むのとかどう?
ref1: https://qiita.com/Damien/items/5f8d4691723b01f370b9
ref2: https://note.com/baketsuhead/n/nd4412a1cd99a

**Comment by Yourein** [comment]
> この回答がどれくらい的を射ているかわからないんだけど、p5js埋め込むのとかどう? ref1: https://qiita.com/Damien/items/5f8d4691723b01f370b9 ref2: https://note.com/baketsuhead/n/nd4412a1cd99a

(根本的な問題解決にはなっていない気がする?)

**Comment by Yourein** [comment]
@TadaTeruki @jugesuke
ガチでどうしようもないなら、ここからネイティブに転向することもまだ出来る。
個人的にはあまりやりたくないけれど… (これはメンバー分けの不明さ、画像処理部分をRustなどで書いてもらったときの繋ぎこみの難易度の不明さ、ネイティブフロントエンドの実装自体の重さに起因する)

どちらにせよ、決断は焦らない程度に早くする必要がある

**Comment by Yourein** [comment]
今日の話し合いをまとめておく。

- 結局Reactはやめることにした
  - Reactを爆破解体(f733f249ba7a9de80543c8df90aa247c9c042859)し、ぺるきのスクラッチフレームワークを乗っけることにした(c5770dc9864359301521717ee8e6798d0a840972)
- Rust wasmは継続して使うことになる。
  - つなぎ込みで困るんじゃないか？とか思ったんだけどよくよく考えたらRust wasmを呼び出す時はjsにされたRustの関数を呼び出す感じだった。(Yourein)

今後はバニラJS + Rustの技術構成で開発していく。

---

@jugesuke @TadaTeruki 技術調査+プロトタイピングありがとう！
