### ISSUE TITLE
Component: Safariでの動作がおかしい

### ISSUE THREAD

**Issue by Yourein** [p2hacks2023/pre-06#29]
PR #26 で発覚したバグ。
YoureinのiPhone SE2のSafariではプレビューURL先のシャッターボタンが押せず、ぺるきのiPad Air(だっけ？)ではシャッターボタン自体は押下できたが、スクラッチ動作の際にページ全体がスクロールする(想定しないという意味での)不具合に遭遇した。

iPhoneに対応していれば様々な人にデモを動かしてくれるかもというメリットがあるので、Youreinとしては対応していると嬉しい。技術検証などを含めて一度みんなで集まる必要がありそう(チーム内でiPhoneを所持、常用しているのがYoureinしかいない)

**Comment by jugesuke** [comment]
修正方法として、技術調査時に実施したのは、Videoタグにいくつかオプションをつけた
これを実施すると治る可能性が高そう

現状の
```html
<video>
```
から、
```html
<video autoplay muted playsinline>
```
とすると動くかも？

今はDOM操作して入れてるはずなので、DOM作成後にオプションを追加すればよさそう
