### ISSUE TITLE
結果のランク分け

### ISSUE THREAD

**Issue by TadaTeruki** [p2hacks2023/pre-06#50]
「メロン級」「ストロベリー級」などの階級についての情報はどうすればいい？
名称・順番・アツさの値の範囲がどこかにまとまっていると嬉しい

値の範囲を決めるのも直感だと難しい気もするので、実装側でデバックしながら決めるでもいい

**Comment by jugesuke** [comment]
- constで境界値を設定できるようにする
- とりあえずは 33% : 33% : 33%

にしておいて、土日の時間で微調整するのが良さそう

**Comment by TadaTeruki** [comment]
了解です
それっぽいことは一応すでにしてる (33%でないけどまあ後で変えればいいでしょう)

階級の名前・境界値・シロップの色

https://github.com/p2hacks2023/pre-06/blob/4efd4432a918afa8f609469b692aeca035deeccb/src/engine/model/grade.ts#L19C1-L26C4

**Comment by TadaTeruki** [comment]
モック用のもので大丈夫そうという感じだった
