### ISSUE TITLE
Document: 熱さの基準を調整する

### ISSUE THREAD

**Issue by Yourein** [p2hacks2023/pre-06#64]
いろいろ試してみた結果、ちょっと熱いと判定する色域と明るさが広すぎる気がする?
あんまり狭くすると今度は撮影場所によって全然遊べない(とくに講堂のような場所でデモできなくなる)ので、適切なラインを探す必要がある。

**Comment by jugesuke** [comment]
こういう黄色でも反応しちゃってる![Screenshot_20231216-113001.png](https://github.com/p2hacks2023/pre-06/assets/103935395/4472a5e0-c23a-461c-9650-5ae538e18f74)

**Comment by Yourein** [comment]
検証1

Hueのrangeを $[0, 30) \cap [330, 360]$ に変更。

**Comment by Yourein** [comment]
https://github.com/p2hacks2023/pre-06/tree/Yourein/amend_hotness_classifying

でテスト

**Comment by Yourein** [comment]
> 検証1
> 
> Hueのrangeを [0,30)∩[330,360] に変更。

これはかなり良い変更。
MOOちゃんはしっかりと体表が切り抜かれなくなった。

この検証1のcommitはrevertせずに、当該コミットからさらなる変更を加えていく。

**Comment by Yourein** [comment]
検証2

まだ焦げ茶色のような暗い、黒に近い色がたまに判定してしまっているため、これを調整したい。
ただし、講堂でデモを行った際に、会場の暗さによってこの変更が致命的なダメージとなりうることに注意する。

**Comment by Yourein** [comment]
かつサンド(文字)の”かつ”の部分が切り抜かれなくなったのは良かった。
ぺるきの顔が切り抜かれるのが悲しい。

**Comment by Yourein** [comment]
天才じゃないのでペールオレンジを弾く方法が思いつかなかった。
そもそも、評価上、ペールオレンジを弾くのは非合理であることが判明した。

したがって、ペールオレンジを弾くことはしない。

**Comment by Yourein** [comment]
検証3

検証2では 30 <= V としていたが実際の色を確認してみたら、50 <= Vでも支障がなさそうだった。
このcommitはrevertする可能性がある。

**Comment by Yourein** [comment]
評価関数が厳しすぎる説が浮上した

**Comment by Yourein** [comment]
検証4

検証1のcommitをrevertしてみた
これで多少ゲーム性は復活したが、やっぱり黄色が持ってこられるのは少し不自然なので、多少黄色側の色域を削る可能性がある。

**Comment by Yourein** [comment]
検証5

$\text{Hue} \in [0, 43] \cup [330, 360]$

と変更を加えた。色域はオレンジと黄色の間から赤色にかけてを含むのと、濃いピンクから赤にかけてを含む。

**Comment by Yourein** [comment]
検証6

検証5で色域はかなりよくなったが、暗い赤がほとんど取れなくなった。
暗い赤を取るために、Valueの値を35から許容するようにした。これでも最初の評価関数よりは厳しくなっている。
