### ISSUE TITLE
「熱さ」ってなに？

### ISSUE THREAD

**Issue by Yourein** [p2hacks2023/pre-06#7]
熱さを計算しなければならないわけだけれども、なにを基準に熱いとしよう？
「赤さ」と言ってもどういう赤さになるのだろう？
画像に含有される赤さ？

**Comment by TadaTeruki** [comment]
こんなもんでどう

## ピクセルの熱さ
$R$: ピクセルのr値 (0.0-1.0)
$G$: ピクセルのg値 (0.0-1.0)
$B$: ピクセルのb値 (0.0-1.0)
$F$: 熱さしきい値  (0.0-1.0) $= 0.5$ くらい？

熱いピクセルの基準: $R-\frac{G+B}{2} > F$


## 全体の熱さ
返り値は百分率(0.0-100.0)であって欲しい(0.0-1.0でもよい)

$N$: ピクセル
$H$: 熱いピクセル

熱い画像の基準: $\frac{len(H)}{len(N)}$

**Comment by Yourein** [comment]
その画像自体の熱さは全体の熱さにある程度のグラデーションを持ったしきい値を設定する感じで良さそう？

**Comment by TadaTeruki** [comment]
画像の熱さにかんしては、そもそもしきい値で区切る必要はなさそうという認識だったんだけど、どうだろう
(撮影中に表示したり、結果として参照・記録するのは百分率なり連続的な値になるかなと)
強いて言うなら、「メロン級」とかの階級にはそれぞれしきい値が必要そうだけど。そこはフロントの仕事になりそうだし

**Comment by Yourein** [comment]
そっか。確かに100分率なんだったらしきい値もなにもないか

**Comment by Yourein** [comment]
暗い画像でも赤を検出できるように、RGB色空間ではなくて、HSV色空間を使いたい。
ぺるきが示してくれた式に合うように考えると以下の通り。

# 熱いピクセル
- $\text{Hue} \in [0～60), [300～360)$
- $\text{Saturation} \in [0.5, 1]$
- $\text{Value} \in [0.1, 1]$
の以上3条件をすべて満たすピクセルを熱いピクセルと呼ぶ

# 全体の熱さ
$N$: 画像のピクセル全体
$H$: 画像の熱いピクセル全体

画像の熱さ: $\dfrac{|H|}{|N|} \times 100$

**Comment by Yourein** [comment]
実装用のメモ: [HSV色空間 - Wikipedia](https://w.wiki/4iYY)
