### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by TadaTeruki** [p2hacks2023/pre-06#9]
# 依存

なし

# 被依存

なし

# プレビュー

![BC77DA46-8B73-4D22-8861-AD4EB1AA2832](https://github.com/p2hacks2023/pre-06/assets/69315285/46be3b92-b59d-4999-af6b-ecc3c7d030ad)
![EED0A42E-CFC0-4B78-B781-5B49367D0366](https://github.com/p2hacks2023/pre-06/assets/69315285/0a8026cb-0a50-4e9b-a716-d00d87c0bb25)

**Comment by jugesuke** [comment]
ホバーで色を変える処理は後で実装する

**Comment by jugesuke** [comment]
使ってみたらいらなさそうなのでホバーはなし
